title: Marjorie Freeman
logo: https://imgur.com/a/lRst0Sl
#textdescription: Ask me why building communities is important when trying to market anything!
show_downloads: true
theme: jekyll-theme-minimal
