title: Marjorie Freeman
logo: https://1drv.ms/i/c/c799fd20a80ae93a/ETrpCqgg_ZkggMe3FAAAAAABxV4hLghP9H2P3P01BTCLUw?e=hEZn0d
#textdescription: Ask me why building communities is important when trying to market anything!
show_downloads: true
theme: jekyll-theme-minimal
