title: Marjorie Freeman
logo: https://1drv.ms/i/c/c799fd20a80ae93a/EfsCG-RF0UdFhAzprxzL_UQBZc--PiV8X99e3GDChKHpUg?e=VV9W0u
#textdescription: Enjoy my portfolio!
show_downloads: true
theme: jekyll-theme-minimal
