title: Marjorie Freeman
logo: "C:\Users\19199\OneDrive\Pictures\Screenshots\Screenshot 2024-02-16 140354.png"
#textdescription: Ask me why building communities is important when trying to market anything!
show_downloads: true
theme: jekyll-theme-minimal
