title: Marjorie Freeman
#logo: https://github.com/account
#textdescription: Ask me why building communities is important when trying to market anything!
show_downloads: true
theme: jekyll-theme-minimal
